analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    unused_field: warning
  exclude:
    - lib/generated/**
    - lib/gen/**

linter:
  rules:
    - depend_on_referenced_packages